# Generated by Django 5.2 on 2025-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
